drop table if exists stats;

create table stats
(
    id integer generated by default as identity,
    app varchar(200) not null,
    uri varchar(200) not null,
    ip varchar(30) not null,
    date timestamp without time zone not null
);